# Generated by Django 5.2.1 on 2025-05-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='agent',
            name='Phone',
            field=models.CharField(default=9207773847, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='Total_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
